// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPumpMVC.Data;

#nullable disable

namespace WebPumpMVC.Migrations
{
    [DbContext(typeof(WebPumpMVCContext))]
    [Migration("20230428092329_NewModel_28.04.2023")]
    partial class NewModel_28042023
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebPumpMVC.Models.Automation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Automation", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.Cap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cap", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.Clamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Diameter")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clamp", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AutomationId")
                        .HasColumnType("int");

                    b.Property<int>("CapId")
                        .HasColumnType("int");

                    b.Property<int>("ClampId")
                        .HasColumnType("int");

                    b.Property<int>("HydraulicAccumulatorId")
                        .HasColumnType("int");

                    b.Property<int>("PipeId")
                        .HasColumnType("int");

                    b.Property<int>("PumpId")
                        .HasColumnType("int");

                    b.Property<int>("PumpsId")
                        .HasColumnType("int");

                    b.Property<int>("RopeId")
                        .HasColumnType("int");

                    b.Property<int>("UnderwaterСableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutomationId");

                    b.HasIndex("CapId");

                    b.HasIndex("ClampId");

                    b.HasIndex("HydraulicAccumulatorId");

                    b.HasIndex("PipeId");

                    b.HasIndex("PumpId");

                    b.HasIndex("RopeId");

                    b.HasIndex("UnderwaterСableId");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.HydraulicAccumulator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HydraulicAccumulator", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("WebPumpMVC.Models.Pipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Diameter")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pipe", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.Pump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("H")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pump", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.Rope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Diameter")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rope", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.UnderwaterСable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Section")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnderwaterСable", (string)null);
                });

            modelBuilder.Entity("WebPumpMVC.Models.Equipment", b =>
                {
                    b.HasOne("WebPumpMVC.Models.Automation", "Automation")
                        .WithMany("Equipments")
                        .HasForeignKey("AutomationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPumpMVC.Models.Cap", "Cap")
                        .WithMany("Equipments")
                        .HasForeignKey("CapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPumpMVC.Models.Clamp", "Clamp")
                        .WithMany("Equipments")
                        .HasForeignKey("ClampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPumpMVC.Models.HydraulicAccumulator", "HydraulicAccumulator")
                        .WithMany("Equipments")
                        .HasForeignKey("HydraulicAccumulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPumpMVC.Models.Pipe", "Pipe")
                        .WithMany("Equipments")
                        .HasForeignKey("PipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPumpMVC.Models.Pump", "Pump")
                        .WithMany("Equipments")
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPumpMVC.Models.Rope", "Rope")
                        .WithMany("Equipments")
                        .HasForeignKey("RopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPumpMVC.Models.UnderwaterСable", "UnderwaterСable")
                        .WithMany("Equipments")
                        .HasForeignKey("UnderwaterСableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automation");

                    b.Navigation("Cap");

                    b.Navigation("Clamp");

                    b.Navigation("HydraulicAccumulator");

                    b.Navigation("Pipe");

                    b.Navigation("Pump");

                    b.Navigation("Rope");

                    b.Navigation("UnderwaterСable");
                });

            modelBuilder.Entity("WebPumpMVC.Models.Automation", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("WebPumpMVC.Models.Cap", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("WebPumpMVC.Models.Clamp", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("WebPumpMVC.Models.HydraulicAccumulator", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("WebPumpMVC.Models.Pipe", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("WebPumpMVC.Models.Pump", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("WebPumpMVC.Models.Rope", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("WebPumpMVC.Models.UnderwaterСable", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
